#!/usr/bin/env python3

import socket
import sys
import subprocess

def client():
    soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = "127.0.0.1"
    port = 65432
    subprocess.call('clear', shell=True)

    try:
        soc.connect((host, port))
    except:
        print("Unable to connect")
        sys.exit()

    print("Enter 'quit' to exit")
    message = input(' -> ')


    while message.upper() != 'QUIT':
    	while message == "":
    		print ('Please enter a message')
    		message = input( ' -> ')
    	soc.sendall(bytes(message, 'utf-8'))
    	message = input(' -> ')

    soc.sendall(bytes(message, 'utf-8'))
    soc.close()

client()
