#!/usr/bin/env python3

import socket
import sys
import subprocess
from threading import Thread

def client_connect():
    try:
        soc.connect((host, port))
    except:
        print("Unable to connect")
        sys.exit()

    print ('*****Welcome to the chat*****')
    print ("Enter 'quit' to exit")
    message = ('')
    try:
        Thread(target=read_thread).start()
    except:
        print ('Unable to create thread')


    while message.upper() != 'QUIT':
        #message = input(' -> ')
    	while message == "":
    		print ('Please enter a message')
    		message = input(' ')
    	soc.sendall(bytes(message, 'utf-8'))
    	message = input(' ')


    soc.sendall(bytes(message, 'utf-8'))
    soc.close()

def read_thread(max_buffer_size = 1024):
    is_active = True

    while is_active:
        server_input = soc.recv(max_buffer_size)
        server_mes = str(server_input.decode('utf-8'))
        print ('::: ' + server_mes)

            #connection.sendall("-".encode("utf8"))

soc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
host = "127.0.0.1"
port = 65432
subprocess.call('clear', shell=True)
client_connect()
